package io;

import model.Model;
import model.Vertex;
import model.Polygon;

import java.io.*;
import java.util.List;

/**
 * Класс для записи 3D моделей в OBJ файлы
 */
public class ObjWriter {
    /**
     * Сохраняет модель в файл
     * @param model модель для сохранения
     * @param filePath путь к файлу
     * @throws IOException если произошла ошибка ввода-вывода
     */
    public static void write(Model model, String filePath) throws IOException {
        File file = new File(filePath);
        

        File parentDir = file.getParentFile();
        if (parentDir != null && !parentDir.exists()) {
            parentDir.mkdirs();
        }

        try (PrintWriter writer = new PrintWriter(new FileWriter(file))) {

            writer.println("# OBJ file generated by ObjWriter");
            writer.println("# Model: " + model.getName());
            writer.println("# Vertices: " + model.getVertexCount());
            writer.println("# Polygons: " + model.getPolygonCount());
            writer.println();

            // Записываем вершины
            List<Vertex> vertices = model.getVertices();
            for (Vertex vertex : vertices) {
                writer.printf("v %.6f %.6f %.6f%n", 
                    vertex.getX(), 
                    vertex.getY(), 
                    vertex.getZ());
            }

            writer.println();


            List<Polygon> polygons = model.getPolygons();
            for (Polygon polygon : polygons) {
                writer.print("f");
                List<Integer> vertexIndices = polygon.getVertexIndices();
                for (Integer index : vertexIndices) {

                    writer.print(" " + (index + 1));
                }
                writer.println();
            }
        }
    }

    /**
     * Сохраняет модель в файл с указанным именем модели в комментарии
     * @param model модель для сохранения
     * @param filePath путь к файлу
     * @param modelName имя модели (будет использовано вместо model.getName())
     * @throws IOException если произошла ошибка ввода-вывода
     */
    public static void write(Model model, String filePath, String modelName) throws IOException {
        String originalName = model.getName();
        model.setName(modelName);
        try {
            write(model, filePath);
        } finally {
            model.setName(originalName);
        }
    }
}
